/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exercicio2;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
/**
 *
 * @author Ngori Januário
 */
public class Es extends javax.swing.JFrame {

    /**
     * Creates new form Es
     */
    public Es() {
        initComponents();
        setIcon();
        setSize(550,418);
        E.setVisible(false);
        JS.setVisible(false);
        JS2.setVisible(false);
        JS3.setVisible(false);
        JS4.setVisible(false);
        JS5.setVisible(false);
        JS6.setVisible(false);
        FJS.setVisible(false);
        Perder.setVisible(false);
        grupo1 = new ButtonGroup();
        //j selecção do jogo
        grupo1.add(j1);
        grupo1.add(j2);
        grupo1.add(j3);
        grupo1.add(j4);
    }
    private ButtonGroup grupo1;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Telas = new javax.swing.JPanel();
        TelaJogar = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        E = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        j1 = new javax.swing.JRadioButton();
        j2 = new javax.swing.JRadioButton();
        j3 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        j4 = new javax.swing.JRadioButton();
        jButton19 = new javax.swing.JButton();
        JS = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        texto = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        texto2 = new javax.swing.JLabel();
        b3 = new javax.swing.JButton();
        Nn = new javax.swing.JLabel();
        b4 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        JS2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        texto1 = new javax.swing.JLabel();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        texto3 = new javax.swing.JLabel();
        b7 = new javax.swing.JButton();
        Nn1 = new javax.swing.JLabel();
        b8 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        JS3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        texto4 = new javax.swing.JLabel();
        b9 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        texto5 = new javax.swing.JLabel();
        b11 = new javax.swing.JButton();
        Nn2 = new javax.swing.JLabel();
        b12 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        JS4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        texto6 = new javax.swing.JLabel();
        b13 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        texto7 = new javax.swing.JLabel();
        b15 = new javax.swing.JButton();
        Nn3 = new javax.swing.JLabel();
        b16 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        JS5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        texto8 = new javax.swing.JLabel();
        b17 = new javax.swing.JButton();
        b18 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        texto9 = new javax.swing.JLabel();
        b19 = new javax.swing.JButton();
        Nn4 = new javax.swing.JLabel();
        b20 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        JS6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        texto10 = new javax.swing.JLabel();
        b21 = new javax.swing.JButton();
        b22 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        texto11 = new javax.swing.JLabel();
        b23 = new javax.swing.JButton();
        Nn5 = new javax.swing.JLabel();
        b24 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        FJS = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        Perder = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        u = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 150));
        setMinimumSize(new java.awt.Dimension(550, 418));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        Telas.setBackground(new java.awt.Color(0, 153, 204));
        Telas.setLayout(null);

        TelaJogar.setBackground(new java.awt.Color(0, 153, 204));
        TelaJogar.setLayout(null);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("Jogar");
        jButton6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        TelaJogar.add(jButton6);
        jButton6.setBounds(80, 150, 140, 17);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Como Jogar?");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        TelaJogar.add(jButton1);
        jButton1.setBounds(80, 190, 140, 17);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Sobre o App");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        TelaJogar.add(jButton2);
        jButton2.setBounds(80, 230, 140, 17);

        jButton17.setBackground(new java.awt.Color(255, 255, 255));
        jButton17.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButton17.setText("X");
        jButton17.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        TelaJogar.add(jButton17);
        jButton17.setBounds(250, 0, 30, 20);

        Telas.add(TelaJogar);
        TelaJogar.setBounds(0, 0, 280, 420);

        E.setBackground(new java.awt.Color(0, 153, 204));
        E.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Selecione o Jogador:");
        E.add(jLabel5);
        jLabel5.setBounds(10, 99, 200, 22);

        j1.setBackground(new java.awt.Color(0, 153, 255));
        j1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        j1.setForeground(new java.awt.Color(255, 255, 255));
        j1.setText("1 Jogador");
        E.add(j1);
        j1.setBounds(20, 130, 110, 25);

        j2.setBackground(new java.awt.Color(0, 153, 255));
        j2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        j2.setForeground(new java.awt.Color(255, 255, 255));
        j2.setText("2 Jogadores");
        E.add(j2);
        j2.setBounds(20, 160, 110, 25);

        j3.setBackground(new java.awt.Color(0, 153, 255));
        j3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        j3.setForeground(new java.awt.Color(255, 255, 255));
        j3.setText("3 Jogadores");
        E.add(j3);
        j3.setBounds(20, 190, 110, 25);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Começar");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        E.add(jButton3);
        jButton3.setBounds(160, 350, 100, 17);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Sair");
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        E.add(jButton4);
        jButton4.setBounds(10, 350, 110, 17);

        j4.setBackground(new java.awt.Color(0, 153, 255));
        j4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        j4.setForeground(new java.awt.Color(255, 255, 255));
        j4.setText("4 Jogadores");
        E.add(j4);
        j4.setBounds(20, 220, 110, 25);

        jButton19.setBackground(new java.awt.Color(255, 255, 255));
        jButton19.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButton19.setText("X");
        jButton19.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        E.add(jButton19);
        jButton19.setBounds(250, 0, 30, 20);

        Telas.add(E);
        E.setBounds(0, 0, 280, 420);

        JS.setBackground(new java.awt.Color(0, 153, 255));
        JS.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nivel 1");
        JS.add(jLabel6);
        jLabel6.setBounds(180, 20, 100, 29);

        texto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 255, 255));
        texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto.setText("\"Longe\"");
        JS.add(texto);
        texto.setBounds(0, 110, 280, 22);

        b1.setBackground(new java.awt.Color(255, 255, 255));
        b1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b1.setText("12-15-14-7-5");
        b1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        JS.add(b1);
        b1.setBounds(20, 140, 110, 20);

        b2.setBackground(new java.awt.Color(255, 255, 255));
        b2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b2.setText("12-5-15-8-4");
        b2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        JS.add(b2);
        b2.setBounds(140, 140, 110, 20);

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton10.setText("Sair");
        jButton10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        JS.add(jButton10);
        jButton10.setBounds(10, 350, 50, 17);

        texto2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        texto2.setForeground(new java.awt.Color(255, 255, 255));
        texto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto2.setText("g=7   e=5   L=12   n=14   o=15");
        JS.add(texto2);
        texto2.setBounds(0, 320, 280, 14);

        b3.setBackground(new java.awt.Color(255, 255, 255));
        b3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b3.setText("11-7-23-8-12");
        b3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        JS.add(b3);
        b3.setBounds(20, 170, 110, 20);

        Nn.setForeground(new java.awt.Color(255, 255, 255));
        Nn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Nn.setText("1 de 6");
        JS.add(Nn);
        Nn.setBounds(180, 50, 80, 16);

        b4.setBackground(new java.awt.Color(255, 255, 255));
        b4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b4.setText("7-9-12-14-15");
        b4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        JS.add(b4);
        b4.setBounds(140, 170, 110, 20);

        jButton21.setBackground(new java.awt.Color(255, 255, 255));
        jButton21.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButton21.setText("X");
        jButton21.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        JS.add(jButton21);
        jButton21.setBounds(250, 0, 30, 20);

        Telas.add(JS);
        JS.setBounds(0, 0, 280, 420);

        JS2.setBackground(new java.awt.Color(0, 153, 255));
        JS2.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nivel 1");
        JS2.add(jLabel7);
        jLabel7.setBounds(180, 20, 100, 29);

        texto1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        texto1.setForeground(new java.awt.Color(255, 255, 255));
        texto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto1.setText("\"Estrada\"");
        JS2.add(texto1);
        texto1.setBounds(0, 110, 280, 22);

        b5.setBackground(new java.awt.Color(255, 255, 255));
        b5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b5.setText("5-19-20-18-1-4-1");
        b5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        JS2.add(b5);
        b5.setBounds(140, 170, 110, 20);

        b6.setBackground(new java.awt.Color(255, 255, 255));
        b6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b6.setText("5-19-21-18-1-4-1");
        b6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        JS2.add(b6);
        b6.setBounds(140, 140, 110, 20);

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton11.setText("Sair");
        jButton11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        JS2.add(jButton11);
        jButton11.setBounds(10, 350, 50, 17);

        texto3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        texto3.setForeground(new java.awt.Color(255, 255, 255));
        texto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto3.setText("a=1   d=4   E=5   r=18   s=19   t=20");
        JS2.add(texto3);
        texto3.setBounds(0, 320, 280, 14);

        b7.setBackground(new java.awt.Color(255, 255, 255));
        b7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b7.setText("5-19-20-18-1-5-1");
        b7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        JS2.add(b7);
        b7.setBounds(20, 170, 110, 20);

        Nn1.setForeground(new java.awt.Color(255, 255, 255));
        Nn1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Nn1.setText("2 de 6");
        JS2.add(Nn1);
        Nn1.setBounds(180, 50, 80, 16);

        b8.setBackground(new java.awt.Color(255, 255, 255));
        b8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b8.setText("5-19-20-11-1-4-1");
        b8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        JS2.add(b8);
        b8.setBounds(20, 140, 110, 20);

        jButton22.setBackground(new java.awt.Color(255, 255, 255));
        jButton22.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButton22.setText("X");
        jButton22.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        JS2.add(jButton22);
        jButton22.setBounds(250, 0, 30, 20);

        Telas.add(JS2);
        JS2.setBounds(0, 0, 280, 420);

        JS3.setBackground(new java.awt.Color(0, 153, 255));
        JS3.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nivel 1");
        JS3.add(jLabel8);
        jLabel8.setBounds(180, 20, 100, 29);

        texto4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        texto4.setForeground(new java.awt.Color(255, 255, 255));
        texto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto4.setText("\"Funciona\"");
        JS3.add(texto4);
        texto4.setBounds(0, 110, 280, 22);

        b9.setBackground(new java.awt.Color(255, 255, 255));
        b9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b9.setText("6-21-14-3-9-15-14-1");
        b9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        JS3.add(b9);
        b9.setBounds(70, 200, 140, 20);

        b10.setBackground(new java.awt.Color(255, 255, 255));
        b10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b10.setText("6-21-14-3-9-12-14-1");
        b10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        JS3.add(b10);
        b10.setBounds(70, 140, 140, 20);

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton12.setText("Sair");
        jButton12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        JS3.add(jButton12);
        jButton12.setBounds(10, 350, 50, 17);

        texto5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        texto5.setForeground(new java.awt.Color(255, 255, 255));
        texto5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto5.setText("a=1   c=3    F=6   i=9   n=14   o=15   u=21");
        JS3.add(texto5);
        texto5.setBounds(0, 320, 280, 14);

        b11.setBackground(new java.awt.Color(255, 255, 255));
        b11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b11.setText("6-21-14-3-9-15-14-11");
        b11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });
        JS3.add(b11);
        b11.setBounds(70, 230, 140, 20);

        Nn2.setForeground(new java.awt.Color(255, 255, 255));
        Nn2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Nn2.setText("3 de 6");
        JS3.add(Nn2);
        Nn2.setBounds(180, 50, 80, 16);

        b12.setBackground(new java.awt.Color(255, 255, 255));
        b12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b12.setText("6-21-11-3-14-1-14-1");
        b12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });
        JS3.add(b12);
        b12.setBounds(70, 170, 140, 20);

        jButton23.setBackground(new java.awt.Color(255, 255, 255));
        jButton23.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButton23.setText("X");
        jButton23.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        JS3.add(jButton23);
        jButton23.setBounds(250, 0, 30, 20);

        Telas.add(JS3);
        JS3.setBounds(0, 0, 280, 420);

        JS4.setBackground(new java.awt.Color(0, 153, 255));
        JS4.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nivel 1");
        JS4.add(jLabel9);
        jLabel9.setBounds(180, 20, 100, 29);

        texto6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        texto6.setForeground(new java.awt.Color(255, 255, 255));
        texto6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto6.setText("\"Vida\"");
        JS4.add(texto6);
        texto6.setBounds(0, 110, 280, 22);

        b13.setBackground(new java.awt.Color(255, 255, 255));
        b13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b13.setText("22-9-4-1");
        b13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });
        JS4.add(b13);
        b13.setBounds(140, 140, 110, 20);

        b14.setBackground(new java.awt.Color(255, 255, 255));
        b14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b14.setText("21-9-4-1");
        b14.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });
        JS4.add(b14);
        b14.setBounds(20, 140, 110, 20);

        jButton13.setBackground(new java.awt.Color(255, 255, 255));
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton13.setText("Sair");
        jButton13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        JS4.add(jButton13);
        jButton13.setBounds(10, 350, 50, 17);

        texto7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        texto7.setForeground(new java.awt.Color(255, 255, 255));
        texto7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto7.setText("a=1   d=4   i=9   V=22");
        JS4.add(texto7);
        texto7.setBounds(0, 320, 280, 14);

        b15.setBackground(new java.awt.Color(255, 255, 255));
        b15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b15.setText("22-9-4-2");
        b15.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });
        JS4.add(b15);
        b15.setBounds(20, 170, 110, 20);

        Nn3.setForeground(new java.awt.Color(255, 255, 255));
        Nn3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Nn3.setText("4 de 6");
        JS4.add(Nn3);
        Nn3.setBounds(180, 50, 80, 16);

        b16.setBackground(new java.awt.Color(255, 255, 255));
        b16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b16.setText("22-9-14-1");
        b16.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });
        JS4.add(b16);
        b16.setBounds(140, 170, 110, 20);

        jButton24.setBackground(new java.awt.Color(255, 255, 255));
        jButton24.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButton24.setText("X");
        jButton24.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        JS4.add(jButton24);
        jButton24.setBounds(250, 0, 30, 20);

        Telas.add(JS4);
        JS4.setBounds(0, 0, 280, 420);

        JS5.setBackground(new java.awt.Color(0, 153, 255));
        JS5.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nivel 1");
        JS5.add(jLabel10);
        jLabel10.setBounds(180, 20, 100, 29);

        texto8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        texto8.setForeground(new java.awt.Color(255, 255, 255));
        texto8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto8.setText("\"Sabes\"");
        JS5.add(texto8);
        texto8.setBounds(0, 110, 280, 22);

        b17.setBackground(new java.awt.Color(255, 255, 255));
        b17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b17.setText("19-1-2-5-19");
        b17.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b17ActionPerformed(evt);
            }
        });
        JS5.add(b17);
        b17.setBounds(20, 140, 110, 20);

        b18.setBackground(new java.awt.Color(255, 255, 255));
        b18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b18.setText("1-19-2-5-19");
        b18.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b18ActionPerformed(evt);
            }
        });
        JS5.add(b18);
        b18.setBounds(140, 140, 110, 20);

        jButton14.setBackground(new java.awt.Color(255, 255, 255));
        jButton14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton14.setText("Sair");
        jButton14.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        JS5.add(jButton14);
        jButton14.setBounds(10, 350, 50, 17);

        texto9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        texto9.setForeground(new java.awt.Color(255, 255, 255));
        texto9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto9.setText("a=1   b=2   e=5   S=19");
        JS5.add(texto9);
        texto9.setBounds(0, 320, 280, 14);

        b19.setBackground(new java.awt.Color(255, 255, 255));
        b19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b19.setText("19-1-5-2-19");
        b19.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b19ActionPerformed(evt);
            }
        });
        JS5.add(b19);
        b19.setBounds(20, 170, 110, 20);

        Nn4.setForeground(new java.awt.Color(255, 255, 255));
        Nn4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Nn4.setText("5 de 6");
        JS5.add(Nn4);
        Nn4.setBounds(180, 50, 80, 16);

        b20.setBackground(new java.awt.Color(255, 255, 255));
        b20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b20.setText("7-9-12-14-15");
        b20.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b20ActionPerformed(evt);
            }
        });
        JS5.add(b20);
        b20.setBounds(140, 170, 110, 20);

        jButton25.setBackground(new java.awt.Color(255, 255, 255));
        jButton25.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButton25.setText("X");
        jButton25.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        JS5.add(jButton25);
        jButton25.setBounds(250, 0, 30, 20);

        Telas.add(JS5);
        JS5.setBounds(0, 0, 280, 420);

        JS6.setBackground(new java.awt.Color(0, 153, 255));
        JS6.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nivel 1");
        JS6.add(jLabel11);
        jLabel11.setBounds(180, 20, 100, 29);

        texto10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        texto10.setForeground(new java.awt.Color(255, 255, 255));
        texto10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto10.setText("\"Fraco\"");
        JS6.add(texto10);
        texto10.setBounds(0, 110, 280, 22);

        b21.setBackground(new java.awt.Color(255, 255, 255));
        b21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b21.setText("6-18-1-3-15");
        b21.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b21ActionPerformed(evt);
            }
        });
        JS6.add(b21);
        b21.setBounds(20, 170, 110, 20);

        b22.setBackground(new java.awt.Color(255, 255, 255));
        b22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b22.setText("6-19-1-3-15");
        b22.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b22ActionPerformed(evt);
            }
        });
        JS6.add(b22);
        b22.setBounds(140, 140, 110, 20);

        jButton15.setBackground(new java.awt.Color(255, 255, 255));
        jButton15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton15.setText("Sair");
        jButton15.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        JS6.add(jButton15);
        jButton15.setBounds(10, 350, 50, 17);

        texto11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        texto11.setForeground(new java.awt.Color(255, 255, 255));
        texto11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto11.setText("a=1   c=3   f=6   o=15   r=18");
        JS6.add(texto11);
        texto11.setBounds(0, 320, 280, 14);

        b23.setBackground(new java.awt.Color(255, 255, 255));
        b23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b23.setText("11-7-23-8-12");
        b23.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b23ActionPerformed(evt);
            }
        });
        JS6.add(b23);
        b23.setBounds(20, 140, 110, 20);

        Nn5.setForeground(new java.awt.Color(255, 255, 255));
        Nn5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Nn5.setText("6 de 6");
        JS6.add(Nn5);
        Nn5.setBounds(180, 50, 80, 16);

        b24.setBackground(new java.awt.Color(255, 255, 255));
        b24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b24.setText("6-18-1-3-16");
        b24.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b24ActionPerformed(evt);
            }
        });
        JS6.add(b24);
        b24.setBounds(140, 170, 110, 20);

        jButton26.setBackground(new java.awt.Color(255, 255, 255));
        jButton26.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButton26.setText("X");
        jButton26.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        JS6.add(jButton26);
        jButton26.setBounds(250, 0, 30, 20);

        Telas.add(JS6);
        JS6.setBounds(0, 0, 280, 420);

        FJS.setBackground(new java.awt.Color(102, 0, 153));
        FJS.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Nivel 2");
        FJS.add(jLabel12);
        jLabel12.setBounds(0, 110, 280, 29);

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton8.setText("Começar");
        jButton8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        FJS.add(jButton8);
        jButton8.setBounds(70, 150, 140, 17);

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton9.setText("Desistir");
        jButton9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        FJS.add(jButton9);
        jButton9.setBounds(70, 180, 140, 17);

        jButton27.setBackground(new java.awt.Color(255, 255, 255));
        jButton27.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButton27.setText("X");
        jButton27.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        FJS.add(jButton27);
        jButton27.setBounds(250, 0, 30, 20);

        Telas.add(FJS);
        FJS.setBounds(0, 0, 280, 420);

        Perder.setBackground(new java.awt.Color(204, 0, 51));
        Perder.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("\"Ups! Voce Perdeu\"");
        Perder.add(jLabel13);
        jLabel13.setBounds(0, 154, 280, 30);

        jButton16.setBackground(new java.awt.Color(255, 255, 255));
        jButton16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton16.setText("Recomeçar");
        jButton16.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        Perder.add(jButton16);
        jButton16.setBounds(60, 190, 160, 17);

        jButton28.setBackground(new java.awt.Color(255, 255, 255));
        jButton28.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButton28.setText("X");
        jButton28.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        Perder.add(jButton28);
        jButton28.setBounds(250, 0, 30, 20);

        Telas.add(Perder);
        Perder.setBounds(0, 0, 280, 420);

        getContentPane().add(Telas);
        Telas.setBounds(270, 0, 280, 420);

        u.setBackground(new java.awt.Color(255, 255, 255));
        u.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exercicio2/851565_665073520170835_41349003_n.png"))); // NOI18N
        u.add(jLabel1);
        jLabel1.setBounds(82, 98, 80, 80);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Jogo Da Mente");
        u.add(jLabel2);
        jLabel2.setBounds(0, 196, 270, 43);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PREMIUM");
        u.add(jLabel3);
        jLabel3.setBounds(-1, 250, 270, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Todos os Direitos reservados");
        u.add(jLabel4);
        jLabel4.setBounds(-2, 275, 270, 14);

        getContentPane().add(u);
        u.setBounds(0, 0, 270, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        TelaJogar.setVisible(false);
        E.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        E.setVisible(false);
        TelaJogar.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Butão sobre o app
        JOptionPane.showMessageDialog(null, "Esta aplicação foi desenvolvida pela EI inc.\nProgramado por Ngori Januário\nVersão 1.0\n Para mais informações entre em eliteinc18.blogspot.com");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Butão como jogar
        JOptionPane.showMessageDialog(null, " O objectivo do jogo é \n" +
" descodificar & codificar\n" +
" os numeros de\n" +
" acordo com\n" +
" o nome dado pela tela.\n" +
" para conseguir\n" +
" jogar o utilizador\n" +
" deverá conhecer o abecedario\n" +
" ou seja saber os numeros\n" +
" das letras.\n" +
" Ex: A é 1 então para codificar\n" +
" o nome Angola\n" +
" basta escrever os numeros\n" +
" de cada letra Ou  seja \n" +
" Angola '114715121' sem deixar\n" +
" espaço");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Butão começar o jogo depois de escolher
        if(j1.isSelected())
        {
            E.setVisible(false);
            JS.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        JS.setVisible(false);
        JS2.setVisible(true);
    }//GEN-LAST:event_b1ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        JS2.setVisible(false);
        JS3.setVisible(true);
    }//GEN-LAST:event_b5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // Butão sair nivel 2 de 10
        JS2.setVisible(false);
        E.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        JS3.setVisible(false);
        JS4.setVisible(true);
    }//GEN-LAST:event_b9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // Butão sair nivel 3 de 10
        JS3.setVisible(false);
        E.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
        JS4.setVisible(false);
        JS5.setVisible(true);
    }//GEN-LAST:event_b13ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // Butão sair nivel 4 de 10
        JS4.setVisible(false);
        E.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void b17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b17ActionPerformed
        JS5.setVisible(false);
        JS6.setVisible(true);
    }//GEN-LAST:event_b17ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // Butão sair nivel 5 de 10
        JS5.setVisible(false);
        E.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void b21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b21ActionPerformed
        JS6.setVisible(false);
        FJS.setVisible(true);
    }//GEN-LAST:event_b21ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // Butão sair nivel 5 de 10
        JS6.setVisible(false);
        E.setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // Butão sair nivel 1 de 10
        JS.setVisible(false);
        E.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // butão desistir do nivel 2
        JOptionPane.showMessageDialog(null, "Fim do Jogo");
        FJS.setVisible(false);
        TelaJogar.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // butão recomeçar com apenas um Jogador
        Perder.setVisible(false);
        E.setVisible(true);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        JS.setVisible(false);
        Perder.setVisible(true);
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        JS.setVisible(false);
        Perder.setVisible(true);
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        JS.setVisible(false);
        Perder.setVisible(true);
    }//GEN-LAST:event_b4ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        JS2.setVisible(false);
        Perder.setVisible(true);
    }//GEN-LAST:event_b8ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        JS2.setVisible(false);
        Perder.setVisible(true);
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        JS2.setVisible(false);
        Perder.setVisible(true);
    }//GEN-LAST:event_b7ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        JS3.setVisible(false);
        Perder.setVisible(true);
    }//GEN-LAST:event_b10ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
        JS3.setVisible(false);
        Perder.setVisible(true);
    }//GEN-LAST:event_b12ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
        JS3.setVisible(false);
        Perder.setVisible(true);
    }//GEN-LAST:event_b11ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
        JS4.setVisible(false);
        Perder.setVisible(true);
    }//GEN-LAST:event_b14ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
        JS4.setVisible(false);
        Perder.setVisible(true);
    }//GEN-LAST:event_b15ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
        JS4.setVisible(false);
        Perder.setVisible(true);
    }//GEN-LAST:event_b16ActionPerformed

    private void b18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b18ActionPerformed
        JS5.setVisible(false);
        Perder.setVisible(true);
    }//GEN-LAST:event_b18ActionPerformed

    private void b19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b19ActionPerformed
        JS5.setVisible(false);
        Perder.setVisible(true);
    }//GEN-LAST:event_b19ActionPerformed

    private void b20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b20ActionPerformed
        JS5.setVisible(false);
        Perder.setVisible(true);
    }//GEN-LAST:event_b20ActionPerformed

    private void b23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b23ActionPerformed
        JS6.setVisible(false);
        Perder.setVisible(true);
    }//GEN-LAST:event_b23ActionPerformed

    private void b22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b22ActionPerformed
        JS6.setVisible(false);
        Perder.setVisible(true);
    }//GEN-LAST:event_b22ActionPerformed

    private void b24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b24ActionPerformed
        JS6.setVisible(false);
        Perder.setVisible(true);
    }//GEN-LAST:event_b24ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton28ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Es.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Es.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Es.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Es.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Es().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel E;
    private javax.swing.JPanel FJS;
    private javax.swing.JPanel JS;
    private javax.swing.JPanel JS2;
    private javax.swing.JPanel JS3;
    private javax.swing.JPanel JS4;
    private javax.swing.JPanel JS5;
    private javax.swing.JPanel JS6;
    private javax.swing.JLabel Nn;
    private javax.swing.JLabel Nn1;
    private javax.swing.JLabel Nn2;
    private javax.swing.JLabel Nn3;
    private javax.swing.JLabel Nn4;
    private javax.swing.JLabel Nn5;
    private javax.swing.JPanel Perder;
    private javax.swing.JPanel TelaJogar;
    private javax.swing.JPanel Telas;
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b17;
    private javax.swing.JButton b18;
    private javax.swing.JButton b19;
    private javax.swing.JButton b2;
    private javax.swing.JButton b20;
    private javax.swing.JButton b21;
    private javax.swing.JButton b22;
    private javax.swing.JButton b23;
    private javax.swing.JButton b24;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JRadioButton j1;
    private javax.swing.JRadioButton j2;
    private javax.swing.JRadioButton j3;
    private javax.swing.JRadioButton j4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel texto;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto10;
    private javax.swing.JLabel texto11;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto3;
    private javax.swing.JLabel texto4;
    private javax.swing.JLabel texto5;
    private javax.swing.JLabel texto6;
    private javax.swing.JLabel texto7;
    private javax.swing.JLabel texto8;
    private javax.swing.JLabel texto9;
    private javax.swing.JPanel u;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        //metodo de por icon
        setIconImage(getToolkit().getImage(getClass().getResource("851565_665073520170835_41349003_n.png")));
    }
}
